# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/enter_btn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.enter_btn = QtWidgets.QPushButton(Form)
        self.enter_btn.setGeometry(QtCore.QRect(130, 80, 41, 32))
        self.enter_btn.setObjectName("enter_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.enter_btn.setText(_translate("Form", "*"))
