# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/master.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Some other example server values are
# server = 'localhost\sqlexpress' # for a named instance
# server = 'myserver,port' # to specify an alternate port



from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QApplication, QDialog, QMainWindow, QMessageBox,QListWidget,QListWidgetItem
)
from utils.utils import db
import pandas as pd

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 740)
        font = QtGui.QFont()
        font.setPointSize(19)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 220, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(260, 150, 421, 411))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(10, 0, 391, 391))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: rgb(255, 170, 252);")
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)#mb change selectin color

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.fill_list()
        self.label.setGeometry(QtCore.QRect(380, 90, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-140, 510, 401, 321))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui/../img/master1.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 120, 181, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("ui/../img/master2.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 610, 141, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("ui/../img/master3.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(700, 10, 251, 181))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("ui/../img/master5.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(680, 400, 281, 231))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("ui/../img/master4.png"))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cотрудники"))
    
    def fill_list(self):
        dbase=db()
        sql=('SELECT ФИО, Работа.Название_услуги as Услуга FROM Сотрудник inner join Работа on Работа.Код_сотрудника = Сотрудник.Код WHERE Статус=%s')
        df = pd.read_sql(sql, dbase.conn,params=['работает'])
        for name in df["ФИО"].unique():
            str=name+" - "+",".join(df[df.ФИО==name]["Услуга"])
            self.listWidget.addItem(str)
        self.listWidget.sortItems()
        dbase.conn.close()

class master(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
