# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QApplication, QDialog, QMainWindow, QMessageBox
)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 740)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 252);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 10, 60, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(760, -10, 261, 751))
        self.label_4.setStyleSheet("background-color: rgb(251, 229, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-30, 0, 261, 751))
        self.label_5.setStyleSheet("background-color: rgb(251, 229, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 20, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 60, 521, 141))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 160, 531, 131))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 270, 601, 901))
        self.label_7.setStyleSheet("background-color: rgb(251, 229, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 320, 531, 351))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("ui/../img/salon-2.png"))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "О «ТОЧКЕ КРАСОТЫ»\n"
"\n"
""))
        self.label_3.setText(_translate("MainWindow", "«Точка Красоты» — это самая крупная сеть салонов beauty-сегмента в \n"
"России. В каждом салоне оказывает услуги парикмахер и маникюрист, в \n"
"некоторых — есть массаж, солярий, косметологи."))
        self.label_6.setText(_translate("MainWindow", "С момента основания в 2012 г. мы развиваем франчайзинговую сеть, \n"
"которая является самой динамично развивающейся сетью \n"
"салонов-парикмахерских в России."))

class about(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
