# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (
    QApplication, QDialog, QMainWindow, QMessageBox
)
import psycopg2
from admin_win.lk_handlers import lk
from admin_win.lk_admin_handlers import lk_admin
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 120, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 50, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 60, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 150, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 190, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.error_label = QtWidgets.QLabel(Dialog)
        self.error_label.setGeometry(QtCore.QRect(150, 90, 60, 16))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        #extra
        self.pushButton.clicked.connect(self.check_data)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Логин"))
        self.label_3.setText(_translate("Dialog", "Пароль"))
        self.pushButton.setText(_translate("Dialog", "Вход"))
    
    def check_data(self):
        if self.lineEdit.text()=='' or self.lineEdit_2.text()=='':
            return
        if self.lineEdit.text()=="admin" and self.lineEdit_2.text()=="admin" :
            win=lk_admin(self)
            self.hide()
            win.show()
        elif self.lineEdit.text()!=self.lineEdit_2.text():
            self.error_label.setText( "ошибка")
        else:
            conn = psycopg2.connect(dbname='салон красоты', user='annasarybaeva', host='localhost')
            cursor = conn.cursor()
            cursor.execute('SELECT Код FROM Сотрудник WHERE Статус=%s',('работает',))
            for row in cursor:
                if int(row[0])==int(self.lineEdit.text()):
                    self.error_label.setText( "вход под сотрудником")
                    self.newWin = lk(self)
                    self.hide()
                    self.newWin.name(row[0])
                    self.newWin.show()   
                    break
                else:
                    self.error_label.setText( "ошибка")
            cursor.close()
            conn.close() 

class auth(QMainWindow, Ui_Dialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
